// <auto-generated />
namespace Fifthweek.Api.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RemoveInUsCentsFromPropertyAndColumnNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveInUsCentsFromPropertyAndColumnNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201507261552027_RemoveInUsCentsFromPropertyAndColumnNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
