// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Fifthweek.Api.Persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ReplaceRefreshTokensManualIndexWithCodeFirstIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReplaceRefreshTokensManualIndexWithCodeFirstIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201501031856056_ReplaceRefreshTokensManualIndexWithCodeFirstIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
